@startuml
class Usuario {
    -[Int] id_usuario
    -[String] nome
    -[StatusUsuario] status
    -[String] endereco
    -[String] numero
    -[Int] cep
    -[String] email
    -[Int] telefone
    -[Int] celular
    -[Int] cpf
    -[Int] rg
    -[Int] cnpj
    -[String] ie
    -[Date] data_registro
 
  .. Construtores ..
    +Usuario()
  .. Getters and Setters ..
    +getIdUsuario()
    +setIdUsuario()
    +...
}
@enduml