@startuml C4_Elements
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml


!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!include DEVICONS/java.puml
!include DEVICONS/mysql.puml
!include DEVICONS/mongodb.puml
!include DEVICONS/react.puml
!include FONTAWESOME/users.puml

LAYOUT_WITH_LEGEND()

title Diagrama de Containers

Person(pessoa, "Pessoa", "Pessoa que usa a Aplicação Web")

System_Ext(third_systems_sensores,"Sistema Terceiros de Sensores", "Sistema de sensores de terceiros")
System_Ext(third_systems_cam,"Sistema Terceiros de Cameras", "Sistema de cameras de terceiros")
System_Ext(email_system,"Sistema de Email", "Servidor de E-mail")

System_Boundary(markab, "Markab System") {
    System_Boundary(maven_project, "Maven") {
        Container(api_gateway,"API", "Java, SpringBoot", "API gateway de acesso e manipulação das entidades do sistema.", $sprite="java")
        Container(log_system,"Sistema de Log", "Java", "Gerenciador de Logs", $sprite="java")
    }

    Container(webapp, "Web App", "ReactJs, Bootstrap, JavaScript", $descr="Portal de Acesso dos Clientes", $sprite="react")
    Container(spa,"SPA", "ReactJs", "Single Page Application", $sprite="react")

    ContainerDb(database, "Database", "MySQL", "Guarda as informações de clientes, usuarios, unidades, areas e componentes.", $sprite="mysql")
    ContainerDb(mongodb, "NoSQL Log Store", "Mongo Db", "Guarda Logs do Sistema", $sprite="mongodb")

    Rel(pessoa, webapp, "Usa", "HTTPS")
    Rel(pessoa, spa, "Navega", "HTTP")

    Rel(third_systems_sensores, api_gateway, "Usa", "HTTPS")
    Rel(third_systems_cam, api_gateway, "Usa", "HTTPS")
    Rel(webapp, api_gateway, "Usa", "HTTPS")

    Rel(spa, email_system, "Usa", "HTTPS")

    Rel(api_gateway, database, "Usa", "SQL")
    Rel(api_gateway, log_system, "Usa", "HTTP")
    Rel(api_gateway, email_system, "Usa", "SMTP")

    Rel(log_system, mongodb, "Usa", "SQL")

    Rel_Back(pessoa, email_system, "Envia e-mail para")
}

@enduml