@startuml

left to right direction

package Markab {
actor "usuariopadrao" as a
 

  usecase (Cadastrar Unidade) as UC1
  usecase (Alterar Unidade) as UC2
  usecase (Excluir unidade) as UC3
  usecase (Relacionar Unidade -> Area) as UC4

}

a --> UC1
a --> UC2
a --> UC3
a --> UC4 

 

@enduml